export default [
	{
	    name: 'adSourcePositionSave',
	    method: 'POST',
	    desc: '广告定位源-添加任务',
	    path: '/adPositionSource/save',
		mock:true,
	    showSuccess: true,
	},
	{
	    name: 'adSourcePositionList',
	    method: 'POST',
	    desc: '广告定位源-列表',
	    path: '/adPositionSource/list',
		mock:true,
	},
	{
	    name: 'adSourcePositionRemove',
	    method: 'POST',
	    desc: '广告定位源-删除',
	    path: '/adPositionSource/remove',
		mock:true,
	    showSuccess: true,
	},
	{
	    name: 'adSourcePositionReCrawl',
	    method: 'POST',
	    desc: '广告定位源-重新发送任务',
	    path: '/adPositionSource/reCrawl',
		mock:true,
	    showSuccess: true,
	},
	{
	    name: 'adSourcePositionCategoryDetails',
	    method: 'POST',
	    desc: '广告定位源-查看分析详情(按类目统计)',
	    path: '/adPositionSource/categoryDetails',
		mock:true,
	},
	{
	    name: 'adSourcePositionProductDetails',
	    method: 'POST',
	    desc: '广告定位源-查看分析详情(按产品统计)',
	    path: '/adPositionSource/productDetails',
		mock:true,
	},
	{
	    name: 'adSourcePositionExportDataByCategory',
	    method: 'POST',
	    desc: '广告定位源-查看分析详情导出(按类目统计)',
	    path: '/adPositionSource/exportDataByCategory',	
		mock:true,
	    showSuccess: true,
	    config:{responseType: "blob"},
	},
	{
	    name: 'adSourcePositionExportDataBy',
	    method: 'POST',
	    desc: '广告定位源-查看分析详情导出(按产品统计)',
	    path: '/adPositionSource/exportDataByProduct',	
		mock:true,
	    showSuccess: true,
	    config:{responseType: "blob"},
	},
	{
	    name: 'adPositionSourceRemoveProduct',
	    method: 'POST',
	    desc: '广告定位源-详情-删除产品',
	    path: '/adPositionSource/removeProduct',
		mock:true,
	    showSuccess: true,
	},
	{
	    name: 'adPositionSourceProductChildDetails',
	    method: 'POST',
	    desc: '查看分析详情(按产品统计)-子ASIN列表',
	    path: '/adPositionSource/productChildDetails',
		mock:true,
	},
]