export default [
	{
	    name: 'adCampaignBrandUpdate',
	    method: 'POST',
	    desc: '品牌广告系列-修改',
	    path: '/adCampaignBrand/update',
	    mock: true,
	    newShowSuccess: true,
	},
	{
	    name: 'adKeywordBrandSave',
	    method: 'POST',
	    desc: '品牌广告关键词-添加',
	    path: '/adKeywordBrand/save',
	    mock: true,
	    newShowSuccess: true,
	},
	{
	    name: 'adKeywordBrandUpdate',
	    method: 'POST',
	    desc: '品牌广告关键词-修改',
	    path: '/adKeywordBrand/update',
	    mock: true,
	    newShowSuccess: true,
	},
	{
	    name: 'adNegativeKeywordBrandList',
	    method: 'POST',
	    desc: '品牌否定词-列表',
	    path: '/adNegativeKeywordBrand/list',
	    mock: true,
	},
	{
	    name: 'adNegativeKeywordBrandSave',
	    method: 'POST',
	    desc: '品牌否定词-添加',
	    path: '/adNegativeKeywordBrand/save',
	    mock: true,
	    newShowSuccess: true,
	},
	{
	    name: 'adNegativeKeywordBrandRemove',
	    method: 'POST',
	    desc: '品牌否定词-删除',
	    path: '/adNegativeKeywordBrand/remove',
	    mock: true,
	    newShowSuccess: true,
	},
]