export default [
    {
        name: 'ebTaskAuctionRankList',
        method: 'POST',
        desc: '任务列表',
        path: '/ebTaskAuctionRank/list',
        mock: true,
        // showSuccess: true,
        params: {},
    },
	{
	    name: 'ebTaskAuctionRankSave',
	    method: 'POST',
	    desc: '添加任务',
	    path: '/ebTaskAuctionRank/save',
	    mock: true,
	    showSuccess: true,
	    params: {},
	},
	{
	    name: 'ebTaskAuctionRankAddMonitor',
	    method: 'POST',
	    desc: '添加监控',
	    path: '/ebTaskAuctionRank/addMonitor',
	    mock: true,
	    showSuccess: true,
	    params: {},
	},
	{
	    name: 'ebTaskAuctionRankUpdateMonitor',
	    method: 'POST',
	    desc: '修改监控',
	    path: '/ebTaskAuctionRank/updateMonitor',
	    mock: true,
	    showSuccess: true,
	    params: {},
	},
	{
	    name: 'ebTaskAuctionRankCancelMonitor',
	    method: 'POST',
	    desc: '取消监控',
	    path: '/ebTasCkAuctionRank/cancelMonitor',
	    mock: true,
	    showSuccess: true,
	    params: {},
	},
	{
	    name: 'ebTaskAuctionRankRemove',
	    method: 'POST',
	    desc: '删除任务',
	    path: '/ebTaskAuctionRank/remove',
	    mock: true,
	    showSuccess: true,
	    params: {},
	},
	{
	    name: 'ebTaskAuctionRankListTaskDetail',
	    method: 'POST',
	    desc: '任务详情列表',
	    path: '/ebTaskAuctionRank/listTaskDetail',
	    mock: true,
	    params: {},
	},
	{
	    name: 'ebTaskAuctionRankCurveList',
	    method: 'POST',
	    desc: '数据分析-曲线展示',
	    path: '/ebTaskAuctionRank/curveList',
	    mock: true,
	    params: {},
	},
	{
	    name: 'ebTaskAuctionRankExportTaskDetail',
	    method: 'POST',
	    desc: '任务详情列表-导出',
	    path: '/ebTaskAuctionRank/exportTaskDetail',
	    mock: true,
		showSuccess: true,
		config:{
			responseType: 'blob'
		},
	    params: {},
	},
	{
	    name: 'ebTaskAuctionRankListItemLocation',
	    method: 'POST',
	    desc: '项目所在地列表',
	    path: '/ebTaskAuctionRank/listItemLocation',
	    mock: true,
	    params: {},
	},
]