export default [
    //类目深度分析
	{
	    name: 'ebTaskCateDepthAysList',
	    method: 'POST',
	    desc: '类目深度分析-列表',
	    path: '/ebTaskCateDepthAys/list',
	    mock: true,
	    // showSuccess: true,
	    params: {},
	},
	{
	    name: 'ebTaskCateDepthAysSave',
	    method: 'POST',
	    desc: '类目深度分析-添加任务',
	    path: '/ebTaskCateDepthAys/save',
	    mock: true,
	    showSuccess: true,
	    params: {},
	},
	{
	    name: 'ebTaskCateDepthAysReCrawl',
	    method: 'POST',
	    desc: '类目深度分析-重新发送任务',
	    path: '/ebTaskCateDepthAys/reCrawl',
	    mock: true,
	    showSuccess: true,
	    params: {},
	},
	{
	    name: 'ebTaskCateDepthAysRemove',
	    method: 'POST',
	    desc: '类目深度分析-删除',
	    path: '/ebTaskCateDepthAys/remove',
	    mock: true,
	    showSuccess: true,
	    params: {},
	},
	{
	    name: 'ebTaskCateDepthAysShopDetails',
	    method: 'POST',
	    desc: '类目深度分析-查看卖家分析详情',
	    path: '/ebTaskCateDepthAys/shopDetails',
	    mock: true,
	    params: {},
	},
	{
	    name: 'ebTaskCateDepthAysExportShopDetails',
	    method: 'POST',
	    desc: '类目深度分析-查看卖家分析详情导出',
	    path: '/ebTaskCateDepthAys/exportShopDetails',
	    mock: true,
		showSuccess:true,
	    params: {},
	},
	{
	    name: 'ebTaskCateDepthAysListToShopDeliveryAddr',
	    method: 'POST',
	    desc: '类目深度分析-查看卖家发货地址详情',
	    path: '/ebTaskCateDepthAys/listToShopDeliveryAddr',
	    mock: true,
	    params: {},
	},
	{
	    name: 'ebTaskCateDepthAysListToCategoryBySeller',
	    method: 'POST',
	    desc: '类目深度分析-查看卖家类目详情',
	    path: '/ebTaskCateDepthAys/listToCategoryBySeller',
	    mock: true,
	    params: {},
	},
	{
	    name: 'ebTaskCateDepthAysListToNewReviewCnByShop',
	    method: 'POST',
	    desc: '类目深度分析-卖家新增评价数',
	    path: '/ebTaskCateDepthAys/listToNewReviewCnByShop',
	    mock: true,
	    params: {},
	},
	{
	    name: 'ebTaskCateDepthAysListToNewOrderCnByShop',
	    method: 'POST',
	    desc: '类目深度分析-卖家新增订单数',
	    path: '/ebTaskCateDepthAys/listToNewOrderCnByShop',
	    mock: true,
	    params: {},
	},
	{
	    name: 'ebTaskCateDepthAysProductDetails',
	    method: 'POST',
	    desc: '类目深度分析-查看产品分析详情',
	    path: '/ebTaskCateDepthAys/productDetails',
	    mock: true,
	    params: {},
	},
	{
	    name: 'ebTaskCateDepthAysExportProductDetails',
	    method: 'POST',
	    desc: '类目深度分析-查看产品分析详情导出',
	    path: '/ebTaskCateDepthAys/exportProductDetails',
	    mock: true,
		showSuccess:true,
	    params: {},
	},
	{
	    name: 'ebTaskCateDepthAysListToNewReviewCnByProduct',
	    method: 'POST',
	    desc: '类目深度分析-产品新增评价数',
	    path: '/ebTaskCateDepthAys/listToNewReviewCnByProduct',
	    mock: true,
	    params: {},
	},
]