export default [
  {
    name: 'rcSaveTask',
    method: 'POST',
    desc: '添加任务',
    showSuccess: true,
    must: ['platformId', 'siteId', 'taskName', 'asins'],
    path: '/rc/saveTask',
  },
  {
    name: 'rcReCrawlTask',
    method: 'POST',
    newShowSuccess: true,
    desc: '重新抓取',
    must: ['platformId', 'siteId', 'taskIds'],
    path: '/rc/reCrawlTask',
  },

  {
    name: 'rcRemoveTask',
    method: 'POST',
    desc: '删除任务',
    newShowSuccess: true,
    must: ['platformId', 'siteId', 'taskIds'],
    path: '/rc/removeTask',
  },
  {
    name: 'rcTaskList',
    method: 'POST',
    desc: '任务列表',
    must: ['platformId', 'siteId'],
    path: '/rc/taskList',
  },
  {
    name: 'rcAsinList',
    method: 'POST',
    desc: '任务Asin列表',
    must: ['platformId', 'siteId', 'taskId'],
    path: '/rc/asinList',
  },
  {
    name: 'rcReview',
    method: 'POST',
    desc: '评价库',
    must: ['platformId', 'siteId', 'flag', 'taskId'],
    path: '/rc/review',
  },
  {
    name: 'rcTranslateReview',
    method: 'POST',
    desc: '评价库翻译',
    showSuccess: true,
    must: ['platformId', 'siteId', 'taskId', 'reviewId'],
    path: '/rc/translateReview',
  },

  {
    name: 'rcExportReview',
    method: 'POST',
    desc: '评价库导出',
    showSuccess: true,
    config: {
      responseType: 'blob',
    },
    singleLoading: true,
    must: ['platformId', 'siteId', 'taskId', 'flag', 'exportType'],
    path: '/rc/exportReview',
  },
  {
    name: 'rcQuestionList',
    method: 'POST',
    desc: 'QA库-问题列表',
    must: ['platformId', 'siteId', 'taskId'],
    path: '/rc/questionList',
  },
  {
    name: 'rcExportQuestion',
    method: 'POST',
    desc: 'QA库-导出问题列表',
    showSuccess: true,
    must: ['platformId', 'siteId', 'taskId', 'questionIds', 'exportType'],
    path: '/rc/exportQuestion',
  },
  {
    name: 'rcAnswerList',
    method: 'POST',
    desc: 'QA库-答案列表',
    must: ['platformId', 'siteId', 'taskId', 'questionId'],
    path: '/rc/answerList',
  },
  {
    name: 'rcTranslateQa',
    method: 'POST',
    desc: 'QA库-翻译',
    showSuccess: true,
    must: ['platformId', 'siteId', 'taskId', 'questionId'],
    path: '/rc/translateQa',
  },
  {
    name: 'rcUpdateAnswer',
    method: 'POST',
    desc: 'QA库-编辑翻译答案',
    showSuccess: true,
    must: ['platformId', 'siteId', 'taskId', 'answerContentCn', 'answerId'],
    path: '/rc/updateAnswer',
  },
]