export default [
	{
		name: 'priceSeoSaveStrategy',
		method: 'POST',
		desc: '添加策略',
		path: '/priceSeo/saveStrategy',
		newShowSuccess:true,
		mock:true,
	},
	{
		name: 'priceSeoStrategyInfo',
		method: 'POST',
		desc: '策略详情',
		path: '/priceSeo/strategyInfo',
		mock:true,
    },
	{
		name: 'priceSeoUpdateStrategy',
		method: 'POST',
		desc: '编辑策略',
		path: '/priceSeo/updateStrategy',
		newShowSuccess:true,
		mock:true,
	},
	{
		name: 'priceSeoUpdateStatus',
		method: 'POST',
		desc: '开启/关闭策略',
		path: '/priceSeo/updateStatus',
		newShowSuccess:true,
		mock:true,
	},
	{
		name: 'priceSeoUpdateDefaultPrice',
		method: 'POST',
		desc: '编辑策略默认售价',
		path: '/priceSeo/updateDefaultPrice',
		newShowSuccess:true,
		mock:true,
	},
	{
		name: 'priceSeoRemove',
		method: 'POST',
		desc: '删除策略',
		path: '/priceSeo/remove',
		newShowSuccess:true,
		mock:true,
	},
	{
		name: 'priceSeoStrategyList',
		method: 'POST',
		desc: '策略列表',
		path: '/priceSeo/strategyList',
		mock:true,
	},
	{
		name: 'priceSeoSeoCrv',
		method: 'POST',
		desc: '策略价格优化曲线',
		path: '/priceSeo/seoCrv',
		mock:true,
	},
	
]
