export default [
    //变体
    {
        name: 'prProductRepoPurchaseVariantGet',
        method: 'POST',
        desc: '获取产品变体',
        path: '/pr/product/repo/purchase/variant/get',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/pr/product/repo/purchase/variant/get'
    },
    {
        name: 'purchasePrProductRepoSetStatus',
        method: 'POST',
        desc: '设置生产状态',
        path: '/pr/product/repo/setStatus',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/pr/product/repo/setStatus',
        showSuccess:true,
    },


    //原材料
    {
        name: 'prProductRepoPartsGet',
        method: 'POST',
        desc: '获取产品配件/原材料',
        path: '/pr/product/repo/parts/get',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/pr/product/repo/parts/get',
        // showSuccess:true,
    },
    {
        name: 'prProductRepoVariantGet',
        method: 'POST',
        desc: '根据产品id。获取该产品和下面的变体',
        path: '/pr/product/repo/variant/get',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/pr/product/repo/variant/get',
        // showSuccess:true,
    },
    {
        name: 'prProductRepoMaterialSave',
        method: 'POST',
        desc: '保存产品原材料',
        path: '/pr/product/repo/material/save',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/pr/product/repo/material/save',
        showSuccess:true,
    },
    {
        name: 'prProductRepoMaterialGet',
        method: 'POST',
        desc: '获取产品原材料',
        path: '/pr/product/repo/material/get',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/pr/product/repo/material/get',
        // showSuccess:true,
    },
    {
        name: 'prProductRepoMaterialDelete',
        method: 'POST',
        desc: '删除产品原材料',
        path: '/pr/product/repo/material/delete',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/pr/product/repo/material/delete',
        showSuccess:true,
    },

    //采购价格
    {
        name: 'prProductRepoPurchaseGet',
        method: 'POST',
        desc: '获取采购信息',
        path: '/pr/product/repo/purchase/get',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/pr/product/repo/purchase/get',
    },
    {
        name: 'prProductRepoPurchaseSupplierGet',
        method: 'POST',
        desc: '获取采购价格列表',
        path: '/pr/product/repo/purchase/supplier/get',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/pr/product/repo/purchase/supplier/get',
    },
    {
        name: 'prProductRepoPurchaseSave',
        method: 'POST',
        desc: '保存采购信息',
        path: '/pr/product/repo/purchase/save',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/pr/product/repo/purchase/save',
        showSuccess:true,
    },
    {
        name: 'purchaseGlEnumList',
        method: 'POST',
        desc: '',
        path: '/GlEnum/list',
        params: {},
        //mockPath:'http://120.79.124.232:8001/mock/187/GlEnum/list',
    },
    {
        name: 'glSelectPurchaseType',
        method: 'POST',
        desc: '供应商采购类型下拉',
        path: '/gl/select/purchaseType',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/gl/select/purchaseType',
    },
    {
        name: 'supplierPeriodGetPeriodList',
        method: 'POST',
        desc: '供应商账期接口下拉',
        path: '/supplier/period/getPeriodList',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/supplier/period/getPeriodList',
    },
    {
        name: 'glSelectPaymentType',
        method: 'POST',
        desc: '供应商付款方式下拉',
        path: '/gl/select/paymentType',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/gl/select/paymentType',
    },
    {
        name: 'supplierAddressGetAddressList',
        method: 'POST',
        desc: '采购点接口下拉',
        path: '/supplier/address/getAddressList',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/supplier/address/getAddressList',
    },
    {
        name: 'purchaseGlAreaGetChild',
        method: 'POST',
        desc: '地区-获取地区列表',
        path: '/GlArea/getChild',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/194/GlArea/getChild',
    },
    {
        name: 'glSupplierSave',
        method: 'POST',
        desc: '添加供应商',
        path: '/gl/supplier/save',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/gl/supplier/save',
        showSuccess :true
    },
    {
        name: 'prProductRepoPurchaseSupplierInfo',
        method: 'POST',
        desc: '获取供应商信息(修改的时候用)',
        path: '/pr/product/repo/purchase/supplier/info',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/pr/product/repo/purchase/supplier/info',
    },
    {
        name: 'prProductRepoPurchaseSupplierSave',
        method: 'POST',
        desc: '保存供应商信息',
        path: '/pr/product/repo/purchase/supplier/save',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/pr/product/repo/purchase/supplier/save',
    },
    {
        name: 'prProductRepoPurchaseSupplierDelete',
        method: 'POST',
        desc: '删除供应商',
        path: '/pr/product/repo/purchase/supplier/delete',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/pr/product/repo/purchase/supplier/delete',
        showSuccess:true,
    },
    {
        name: 'prProductRepoPurchaseSupplierSetStatus',
        method: 'POST',
        desc: '设置供应商产品状态',
        path: '/pr/product/repo/purchase/supplier/set/status',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/pr/product/repo/purchase/supplier/set/status',
        showSuccess:true,
    },

    //产品头程
    {
        name: 'prProductRepoFirstTransportGet',
        method: 'POST',
        desc: '获取产品头程',
        path: '/pr/product/repo/first/transport/get',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/pr/product/repo/first/transport/get',
    },
    {
        name: 'glFirstTransportGetComboBox',
        method: 'POST',
        desc: '获取产品头程',
        path: '/gl/first/transport/getComboBox',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/gl/first/transport/getComboBox',
    },
    {
        name: 'glFirstTransportRemove',
        method: 'POST',
        desc: '删除头程',
        path: '/gl/first/transport/remove',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/gl/first/transport/remove',
        showSuccess : true
    },
    {
        name: 'FirstTransportGlTransportationList',
        method: 'POST',
        desc: '运输方-获取列表',
        path: '/GlTransportation/list',
        params: {},
        // mockPath:'http://120.79.124.232:8001/mock/187/gl/first/transport/remove',
        // showSuccess : true
    },
    {
        name: 'FirstTransportGlTransportTypeList',
        method: 'POST',
        desc: '运输方式-获取列表',
        path: '/GlTransportType/list',
        params: {},
        // mockPath:'http://120.79.124.232:8001/mock/187/gl/first/transport/remove',
        // showSuccess : true
    },
    {
        name: 'glFirstTransportSave',
        method: 'POST',
        desc: '保存头程',
        path: '/gl/first/transport/save',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/gl/first/transport/save',
        showSuccess : true
    },
    {
        name: 'prProductRepoFirstTransportDelete',
        method: 'POST',
        desc: '删除产品头程',
        path: '/pr/product/repo/first/transport/delete',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/pr/product/repo/first/transport/delete',
        showSuccess : true
    },
    {
        name: 'prProductRepoFirstTransportSave',
        method: 'POST',
        desc: '保存产品头程',
        path: '/pr/product/repo/first/transport/save',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/pr/product/repo/first/transport/save',
        showSuccess : true
    },
    {
        name: 'glFirstTransportInfo',
        method: 'POST',
        desc: '保存产品头程',
        path: '/gl/first/transport/info',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/gl/first/transport/info',
       // showSuccess : true
    },
    {
        name: 'glFirstTransportUpdate',
        method: 'POST',
        desc: '编辑头程',
        path: '/gl/first/transport/update',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/gl/first/transport/update',
        showSuccess : true
    },

    //报关信息
    {
        name: 'prProductRepoPurchaseCountryGet',
        method: 'POST',
        desc: '获取国家配置',
        path: '/pr/product/repo/purchase/country/get',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/pr/product/repo/purchase/country/get',
        //showSuccess : true
    },
    {
        name: 'prProductRepoPurchaseCountryUpdate',
        method: 'POST',
        desc: '修改国家配置',
        path: '/pr/product/repo/purchase/country/update',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/pr/product/repo/purchase/country/update',
        showSuccess : true
    },
    {
        name: 'glCustomsCountryList',
        method: 'POST',
        desc: '获取报关计价规则',
        path: '/gl/customs/country/list',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/gl/customs/country/list',
       // showSuccess : true
    },
    {
        name: 'glCustomsCountryUpdate',
        method: 'POST',
        desc: '修改报关计价规则',
        path: '/gl/customs/country/update',
        params: {},
        mockPath:'http://120.79.124.232:8001/mock/187/gl/customs/country/update',
        showSuccess : true
    },
]