export default [
    {
        name: 'ebTaskKrResearchList',
        method: 'POST',
        desc: '任务列表',
        path: '/ebTaskKrResearch/list',
        mock: true,
        // showSuccess: true,
        params: {},
    },
	{
	    name: 'ebTaskKrResearchSave',
	    method: 'POST',
	    desc: '添加任务',
	    path: '/ebTaskKrResearch/save',
	    mock: true,
	    showSuccess: true,
	    params: {},
	},
	{
	    name: 'ebTaskKrResearchAddMonitor',
	    method: 'POST',
	    desc: '添加监控',
	    path: '/ebTaskKrResearch/addMonitor',
	    mock: true,
	    showSuccess: true,
	    params: {},
	},
	{
	    name: 'ebTaskKrResearchUpdateMonitor',
	    method: 'POST',
	    desc: '修改监控',
	    path: '/ebTaskKrResearch/updateMonitor',
	    mock: true,
	    showSuccess: true,
	    params: {},
	},
	{
	    name: 'ebTaskKrResearchCancelMonitor',
	    method: 'POST',
	    desc: '取消监控',
	    path: '/ebTaskKrResearch/cancelMonitor',
	    mock: true,
	    showSuccess: true,
	    params: {},
	},
	{
	    name: 'ebTaskKrResearchRemove',
	    method: 'POST',
	    desc: '删除任务',
	    path: '/ebTaskKrResearch/remove',
	    mock: true,
	    showSuccess: true,
	    params: {},
	},
	{
	    name: 'ebTaskKrResearchListTaskDetail',
	    method: 'POST',
	    desc: '任务详情列表',
	    path: '/ebTaskKrResearch/listTaskDetail',
	    mock: true,
	    // showSuccess: true,
	    params: {},
	},
]