export default [
  
  '/product/productList/addProduct.html',
  '/product/productList/editProduct.html',
  '/product/productList/importMaterialProduct.html',
  '/product/productList/editShopProduct.html',
  '/product/ModifyChannelAssociations.html',
  '/product/ProductCategoryManagement.html',
  '/product/SensitiveKeyword.html',
  '/product/SkuGenerationRules.html',
  '/product/SkuPlatformTitle.html',
  '/product/StoreManagement.html',
  '/product/productList/editPurchase.html',
  '/intelligentReplenishment.html',
  '/product/MaterialWrap.html',
  '/product/MaterialWrap.html',
  '/product/ShopProducts/moveLog.html',
  '/product/ToSellStrategy.html',

  '/product/BrandManagement.html',
  '/product/SupplierManagement.html',

  '/product/productList/addProduct.html:id',
  '/product/imageLibrary.html:id',
  '/product/imageLibrary.html',
  '/product/productList/editPurchase.html:id',
  '/product/productList/editProduct.html:id',
  '/product/platformList/viewProduct.html:id',
  '/product/platformList/uploadProduct.html:id',
  '/product/platformList/editLists.html:id',
  '/product/platformList/ebayEditLists.html:id',
  '/product/platformList/wishEditLists.html:id',
  '/product/platformList/review.html:id',
  '/product/ShopProducts/editLists.html:id',
  '/product/productList/editAll.html:id',
  '/product/productList/editVariant.html:id',
  '/product/productList/viewProduct.html:id',
  '/product/productList/viewProductVariant.html:id',
  '/product/ShopProducts/reviewEditLists.html:id',
  
]
